# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_sentemail_address_forwarding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentemail',
            name='unsub_ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='verif_ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
    ]
